name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: cd .. && sudo mv BrickLinux /mnt/ && cd /mnt && sudo mv BrickLinux lfs && cd lfs && sudo bash build_env/version-check.sh && export LFS=/mnt/lfs && export DIST_ROOT=$LFS/build_env && sudo -E bash build_env/prepare.sh

  world:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: bash build_env/version-check.sh
