name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sudo bash build_env/version-check.sh

      - name: Run a one-line
        run: export LFS=/mnt/lfs && export DIST_ROOT=$LFS/build_root
       
      - name: Run a multi-line script
        run: |
          sudo bash -E build_env/prepare.sh
          echo test, and deploy your project.

  world:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: sudo bash build_env/version-check.sh
